language: python

python:
  - "2.7"
  - "3.4"

install:
  - pip install flake8
  - pip install coverage
  - python setup.py install

script:
  - python setup.py test
  - find . -type f -name "*.py" | xargs flake8

after_success:
  - coverage run --source pygeometa setup.py test
  - coverage report -m
